### ISSUE TITLE
Unable to visualize diagrams

### ISSUE THREAD

**Issue by TeoDema-tech** [borkdominik/bigER#31]
### Description

As title, I am unable to visualize any diagrams in the application, nor create new ones, same goes for the relationships

### Current Behavior

Not Working

### Environment

-Linux(Manjaro, GNOME,latest version)
-OpenJDK 18

### Additional Information

debug log from extension output:

Error during request: : java.lang.RuntimeException: Cannot create a resource for 'file:///home/matteo/Documenti/test'; a registered resource factory is needed
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:263)
	at org.eclipse.xtext.ide.server.ProjectManager.getResource(ProjectManager.java:181)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:436)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:1116)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by TeoDema-tech** [comment]
Yes, the issue presents itself whenever i try to open up an .erd file, even the tsst one initialized by `New Sample ER Model`

**Comment by LeData** [comment]
I have the same issue. To be able to get the plugin to initialize, I need to create a new file and then copy paste the content I saved previously.

**Comment by TeoDema-tech** [comment]
Found the issue: when creating a new diagram with the command  `New Sample ER Model` you HAVE to attach the file extension EG: `test.erd` as the save as feature doesn't do this automatically

**Comment by LeData** [comment]
Quick note on that. 
@TeoDema-tech : Thanks for the tip. I had all my files saved as `.erd` so that wasn't the issue for me.

Luckily, I discovered that performing `ctrl+o` with an erd file selected in the explorer panel directly opened the file WITH the viz.
Performing a general `ctrl+o` and selecting the `.erd` file via the pop-up file selector doesn't trigger the viz.

Hope that helps other that were copy pasting  dozen of times like me.
Cheers!
