### ISSUE TITLE
Couldn't start client ERDiagram Language Server 

### ISSUE THREAD

**Issue by AkaiKenshi** [borkdominik/bigER#67]
### Description

can't use the tool due to this error 

output: 
```
[Error - 2:51:50 AM] Starting client failed
Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Users\nacho\.vscode\extensions\bigmodelingtools.erdiagram-0.5.0\pack\main.js:13639:40
```

### Steps to Reproduce

1. on Startup 

### Environment

-OS: Windows 
-JAVA: openjdk 11.0.16.1 2022-08-12 LTS
-VSCode: 1.92.2

**Comment by PedroBlanco** [comment]
### Description

Same error: plugin not loading.

### Current Behavior

1. Error dialogs:
![imagen](https://github.com/user-attachments/assets/9e7b33cf-323a-4f35-b1fe-4331f0c8d15e)
2. Output:
`
[Error - 1:26:11 PM] Starting client failed
Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Usuarios\pedro\.vscode\extensions\bigmodelingtools.erdiagram-0.5.0\pack\main.js:13639:40
`

### Expected Behavior

1. Dialog saying that it has been correctly loaded.

### Steps to Reproduce

1. On opening an `.erd` file

### Environment

Same machine with:
* OS: Windows 11
* JAVA:
  * openjdk 22.0.2
  * Liberica Standard JDK 21.0.4+9 x86 64 for Windows
  * Liberica Standard JRE 22.0.2+11 x86 64 for Windows
  * Microsoft JDK 21.0.4 x64
* VSCode: 1.92.2

**Comment by GOKU900** [comment]
I was having the same issue. I was on VS code August 2024 (version 1.93). I reverted to VS code June 2024 (version 1.91)
and did not see the error under this version and "bigER Modeling Tool v0.5.0".

**Comment by giuliano-marinelli** [comment]
Any solution for this problem with new VS Code versions?

**Comment by rajabhathor** [comment]
I have the same issue - trying to use for a Pharma Client

**Comment by borkdominik** [comment]
I cannot reproduce this with the current version of VS Code and Java 21 on Mac.
We will look into this, might be a Windows issue @plglaser

**Comment by AdamBanham** [comment]
I can also confirm the issue is occurring on Windows, with a fresh install from the extensions tab in vscode. 
![image](https://github.com/user-attachments/assets/308e9718-fac4-41e7-af69-60fc54ce5f5b)

## Expected Behavior
Dialog saying that it has been correctly loaded.
## Steps to Reproduce
On opening an .erd file
## Environment
OS: Windows 11 Pro 10.0.26100
JAVA:
openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.4.0+7-1) (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.4.0+7-1) (build 21.0.4+7-LTS, mixed mode, sharing)
VSCode: 1.95.3
## Possible Issue
I think the issue is likely connected to a recent CVE which then triggered a breaking change for nodejs, which vscode has since moved to from v1.92.
A rundown of the breaking changes can be seen in the following issues:
- Nodejs introduces breaking changes https://github.com/nodejs/node/issues/52554
- Vscode moves to electron 30 and updates Nodejs, which includes the breaking change to spawning https://github.com/gitkraken/vscode-gitlens/issues/3387

The previous issue outlines the changes required to adjust and resolve the issue in the immediate future (https://github.com/gitkraken/vscode-gitlens/issues/3387) as outlined below:

> Node.js has added a section on [batch file spawning](https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows) to their documentation. To fix any issues:
> - Find locations where you call child_process.spawn to execute a batch file on Windows
> - Add shell: true or shell: process.platform === 'win32' to the options object
>    - If the batch script path may contain spaces, you will also need to wrap the path in quotation marks.

I have not tested the suggested changes, but do have some time if you would like me to test the possible resolution with a PR.

**Comment by Zhengwei5360** [comment]
@AdamBanham , Hi Adam, I just met this kind of issue , and is there any workaround to solve it ? thanks ~

**Comment by AdamBanham** [comment]
@Zhengwei5360 

> @AdamBanham , Hi Adam, I just met this kind of issue , and is there any workaround to solve it ? thanks ~

I am unsure if there is any work around if you installing the extension from the marketplace. My PR (https://github.com/borkdominik/bigER/pull/69) was able to build the extension locally if you wanted to setup the dev environment and rebuild the extension yourself.
